# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-28 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('discriprion', tinymce.models.HTMLField(verbose_name='\u63cf\u8ff0')),
                ('status', models.BooleanField(default=False, verbose_name='\u72b6\u6001')),
                ('sequence', models.IntegerField(verbose_name='\u6392\u5e8f')),
            ],
            options={
                'db_table': 'wh_area',
                'verbose_name': '\u5730\u533a\u5206\u7c7b',
                'verbose_name_plural': '\u5730\u533a\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('discriprion', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('status', models.BooleanField(default=False, verbose_name='\u72b6\u6001')),
                ('sequence', models.IntegerField(verbose_name='\u6392\u5e8f')),
            ],
            options={
                'db_table': 'wh_profession',
                'verbose_name': '\u884c\u4e1a\u5206\u7c7b',
                'verbose_name_plural': '\u884c\u4e1a\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='PublicNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('logo', models.ImageField(upload_to=b'public_logo/%Y/%m', verbose_name='\u5fae\u4fe1logo')),
                ('QR_code', models.ImageField(upload_to=b'code/%Y/%m', verbose_name='\u4e8c\u7ef4\u7801')),
                ('wechat_number', models.CharField(max_length=50, verbose_name='\u5fae\u4fe1\u53f7')),
                ('website', models.CharField(max_length=100, verbose_name='\u7f51\u5740')),
                ('wechat_origin_number', models.CharField(max_length=50, verbose_name='\u539f\u59cb\u53f7')),
                ('keywords', models.CharField(max_length=100, verbose_name='\u5173\u952e\u8bcd')),
                ('recommend', models.CharField(choices=[(1, '\u4e00\u661f'), (2, '\u4e8c\u661f'), (3, '\u4e09\u661f'), (4, '\u56db\u661f'), (5, '\u4e94\u661f')], default=1, max_length=20, verbose_name='\u63a8\u8350\u6307\u6570')),
                ('introduction', models.TextField(verbose_name='\u7b80\u4ecb')),
                ('is_check', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5ba1\u6838')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Area', verbose_name='\u5730\u533a')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Profession', verbose_name='\u884c\u4e1a')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u5e03\u4eba')),
            ],
            options={
                'db_table': 'wh_publicnumber',
                'verbose_name': '\u516c\u4f17\u53f7',
                'verbose_name_plural': '\u516c\u4f17\u53f7',
            },
        ),
    ]
