# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('image', models.ImageField(upload_to='ad/index', verbose_name='\u8def\u5f84')),
                ('url', models.CharField(max_length=100, verbose_name='\u5730\u5740')),
            ],
            options={
                'db_table': 'wh_ad',
                'verbose_name': '\u5e7f\u544a',
                'verbose_name_plural': '\u5e7f\u544a',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('image', models.ImageField(upload_to='ad/index', verbose_name='\u8def\u5f84')),
                ('url', models.CharField(max_length=100, verbose_name='\u5730\u5740')),
            ],
            options={
                'db_table': 'wh_banner',
                'verbose_name': '\u9996\u9875\u8f6e\u64ad',
                'verbose_name_plural': '\u9996\u9875\u8f6e\u64ad',
            },
        ),
    ]
