# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('is_delete', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('keywords', models.CharField(max_length=100, verbose_name='\u5173\u952e\u8bcd')),
                ('content', tinymce.models.HTMLField(verbose_name='\u5185\u5bb9')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='\u63a8\u8350')),
                ('is_check', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5ba1\u6838')),
            ],
            options={
                'db_table': 'wh_article',
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('discriprion', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('status', models.BooleanField(default=False, verbose_name='\u72b6\u6001')),
                ('sequence', models.IntegerField(verbose_name='\u6392\u5e8f')),
            ],
            options={
                'db_table': 'wh_atriclecategory',
                'verbose_name': '\u6587\u7ae0\u5206\u7c7b',
                'verbose_name_plural': '\u6587\u7ae0\u5206\u7c7b',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleCategory', verbose_name='\u5206\u7c7b'),
        ),
    ]
